# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-19 13:25
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationModel3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('commentator', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Model evaluations',
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('view_counter', models.IntegerField(default=0, editable=False)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model 3D',
                'verbose_name_plural': 'Models 3D',
            },
        ),
        migrations.AddField(
            model_name='evaluationmodel3d',
            name='model_3d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Model3D'),
        ),
    ]
