# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
