# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-19 23:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_auto_20170219_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationmodel3d',
            name='evaluation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
    ]
